### ISSUE TITLE
Removed `id="add-contact"` breaks e2e tests downstream

### ISSUE THREAD

**Issue by cnishina** [testing-angular-applications/contacts-app-starter#14]
This commit is breaking my tests https://github.com/testing-angular-applications/contacts-app-starter/commit/87c8e295407f651c3c27f6a5991452cefbcdb390 downstream. Should have Protractor tests included in CI

**Comment by jesselpalmer** [comment]
sorry about that. i should have asked you to take a look at it before i made that change.
